import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import PlaygroundHomeScreen from '../HomeScreen';
import { prototypes } from '../prototypes';

// Screens are auto-discovered (see src/prototypes.ts). Adding a prototype folder
// registers its screen automatically — do not edit this file to add one.
// Screen names cannot be statically enumerated, so the param list is generic.
export type RootParamList = Record<string, undefined>;

const Stack = createNativeStackNavigator<RootParamList>();

export default function AppNavigator() {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="PlaygroundHome"
        component={PlaygroundHomeScreen}
        options={{ headerShown: false }}
      />
      {prototypes.map((p) => (
        <Stack.Screen
          key={p.route}
          name={p.route}
          component={p.component}
          options={
            p.headerShown
              ? {
                  title: p.label,
                  headerBackTitle: 'Playground',
                  headerStyle: { backgroundColor: '#006add' },
                  headerTintColor: '#ffffff',
                  headerTitleStyle: { fontWeight: '600' },
                }
              : { headerShown: false }
          }
        />
      ))}
    </Stack.Navigator>
  );
}
