export const rooms = [
  // Standard Twin — Floor 1 (numeric room numbers)
  { id: '1',  number: '101', floor: 1, type: 'Standard Twin',   status: 'CLEANED',       assignedTo: 'Maria S.', notes: null, bedConfiguration: 'Twin Beds' },
  { id: '2',  number: '102', floor: 1, type: 'Standard Twin',   status: 'UNCLEANED',     assignedTo: 'Maria S.', notes: null, bedConfiguration: 'Twin Beds' },
  { id: '3',  number: '103', floor: 1, type: 'Standard Twin',   status: 'SKIP_CLEANING', assignedTo: null,       notes: 'Guest requested no service', bedConfiguration: 'Twin Beds' },
  { id: '4',  number: '104', floor: 1, type: 'Standard Twin',   status: 'UNCLEANED',     assignedTo: 'James T.', notes: null, bedConfiguration: 'Twin Beds' },
  // Double Room — descriptive names (no unique room number)
  { id: '5',  number: 'Basic Double Room 1', floor: 2, type: 'Double Room', status: 'CLEANED',       assignedTo: 'James T.', notes: null, bedConfiguration: 'King (Twins Combined)' },
  { id: '6',  number: 'Basic Double Room 2', floor: 2, type: 'Double Room', status: 'UNCLEANED',     assignedTo: 'Anna K.',  notes: 'Late checkout', bedConfiguration: 'King (Twins Combined)' },
  { id: '7',  number: 'Basic Double Room 3', floor: 2, type: 'Double Room', status: 'CLEANED',       assignedTo: 'Anna K.',  notes: null, bedConfiguration: 'King (Twins Combined)' },
  { id: '8',  number: 'Basic Double Room 4', floor: 2, type: 'Double Room', status: 'SKIP_CLEANING', assignedTo: null,       notes: 'Do not disturb', bedConfiguration: 'King (Twins Combined)' },
  // Suite — individually numbered descriptive names
  { id: '9',  number: 'Budget Studio 1',          floor: 3, type: 'Suite', status: 'UNCLEANED',     assignedTo: 'Maria S.', notes: null, bedConfiguration: 'King (Twins Combined)' },
  { id: '10', number: 'Budget Studio 2',          floor: 3, type: 'Suite', status: 'CLEANED',       assignedTo: 'James T.', notes: null, bedConfiguration: 'King (Twins Combined)' },
  { id: '11', number: 'Budget Studio 3',          floor: 3, type: 'Suite', status: 'UNCLEANED',     assignedTo: 'Anna K.',  notes: null, bedConfiguration: 'King (Twins Combined)' },
  { id: '12', number: 'Budget Studio - Upstairs', floor: 3, type: 'Suite', status: 'CLEANED',       assignedTo: 'Maria S.', notes: null, bedConfiguration: 'King (Twins Combined)' },
  // Dorm — hostel-style bed names
  { id: '13', number: 'Bed in 10-Bed 1', floor: 4, type: 'Dorm', status: 'CLEANED',       assignedTo: 'James T.', notes: null, bedConfiguration: 'Single Bed' },
  { id: '14', number: 'Bed in 10-Bed 2', floor: 4, type: 'Dorm', status: 'UNCLEANED',     assignedTo: 'Anna K.',  notes: null, bedConfiguration: 'Single Bed' },
  { id: '15', number: 'Bed in 10-Bed 3', floor: 4, type: 'Dorm', status: 'SKIP_CLEANING', assignedTo: null,       notes: 'VIP — no service', bedConfiguration: 'Single Bed' },
  { id: '16', number: 'Bed in 10-Bed 4', floor: 4, type: 'Dorm', status: 'CLEANED',       assignedTo: 'Maria S.', notes: null, bedConfiguration: 'Single Bed' },
];

export const reservations = [
  // ── Calendar reservations ──
  { id: 'r1',  roomId: '1',  guestName: 'Smith, John',    checkIn: '2026-03-22', checkOut: '2026-03-28', adults: 2, children: 1, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Standard Twin)',  lateCheckout: false, bedConfiguration: null },
  { id: 'r2',  roomId: '2',  guestName: 'Connor, Sarah',  checkIn: '2026-03-28', checkOut: '2026-04-02', adults: 1, children: 0, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Standard Twin)',  lateCheckout: false, bedConfiguration: null },
  { id: 'r3',  roomId: '3',  guestName: 'Johnson, Mike',  checkIn: '2026-03-27', checkOut: '2026-03-29', adults: 2, children: 0, infants: 0, reservationStatus: 'TENTATIVE',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Standard Twin)',  lateCheckout: false, bedConfiguration: null },
  { id: 'r4',  roomId: '4',  guestName: 'Davis, Emily',   checkIn: '2026-03-26', checkOut: '2026-03-30', adults: 2, children: 2, infants: 1, reservationStatus: 'CONFIRMED',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Standard Twin)',  lateCheckout: false, bedConfiguration: 'Baby Cot Added' },
  { id: 'r5',  roomId: '5',  guestName: 'Brown, Robert',  checkIn: '2026-03-20', checkOut: '2026-03-27', adults: 3, children: 0, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room)',    lateCheckout: false, bedConfiguration: null },
  { id: 'r6',  roomId: '6',  guestName: 'White, Lisa',    checkIn: '2026-03-23', checkOut: '2026-03-27', adults: 2, children: 1, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room)',    lateCheckout: true,  bedConfiguration: null },
  { id: 'r15', roomId: '8',  guestName: 'Antetokounmpo, Giannis', checkIn: '2026-03-24', checkOut: '2026-03-27', adults: 2, children: 1, infants: 1, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room)',    lateCheckout: true,  bedConfiguration: null },
  { id: 'r7',  roomId: '7',  guestName: 'Wilson, Tom',    checkIn: '2026-03-28', checkOut: '2026-03-31', adults: 1, children: 0, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room)',    lateCheckout: false, bedConfiguration: null },
  { id: 'r8',  roomId: '9',  guestName: 'Lee, Jessica',   checkIn: '2026-03-18', checkOut: '2026-04-01', adults: 2, children: 2, infants: 1, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Suite)',          lateCheckout: false, bedConfiguration: 'Baby Cot Added' },
  { id: 'r9',  roomId: '10', guestName: 'Clark, David',   checkIn: '2026-03-27', checkOut: '2026-03-31', adults: 2, children: 0, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Suite)',          lateCheckout: false, bedConfiguration: null },
  { id: 'r10', roomId: '11', guestName: 'Irving, Kyrie',  checkIn: '2026-03-23', checkOut: '2026-03-28', adults: 2, children: 1, infants: 1, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Suite)',          lateCheckout: false, bedConfiguration: 'Baby Cot Added' },
  { id: 'r11', roomId: '12', guestName: 'Irving, Kyrie',  checkIn: '2026-03-27', checkOut: '2026-04-01', adults: 2, children: 0, infants: 0, reservationStatus: 'TENTATIVE',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Suite)',          lateCheckout: false, bedConfiguration: null },
  { id: 'r12', roomId: '13', guestName: 'Taylor, James',  checkIn: '2026-03-21', checkOut: '2026-03-26', adults: 4, children: 2, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Dorm)',           lateCheckout: true,  bedConfiguration: 'Extra Bed Added' },
  { id: 'r13', roomId: '14', guestName: 'Martin, Sofia',  checkIn: '2026-03-27', checkOut: '2026-04-02', adults: 2, children: 0, infants: 0, reservationStatus: 'TENTATIVE',  guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Dorm)',           lateCheckout: false, bedConfiguration: null },
  { id: 'r14', roomId: '16', guestName: 'Garcia, Carlos', checkIn: '2026-03-24', checkOut: '2026-03-29', adults: 3, children: 1, infants: 0, reservationStatus: 'CONFIRMED',  guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Dorm)',           lateCheckout: false, bedConfiguration: null },

  // ── Today's reservations (for Reservations page) ──
  { id: 'today-out-1', roomId: '1',  guestName: 'Torff, Kierra',       checkIn: '2026-03-06', checkOut: '2026-03-09', adults: 3, children: 0, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room Deluxe)', lateCheckout: false, bedConfiguration: null },
  { id: 'today-in-1',  roomId: '2',  guestName: 'Saris, Haylie',       checkIn: '2026-03-09', checkOut: '2026-05-03', adults: 2, children: 1, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: 1456.09, paymentExpired: true,  roomDisplayName: 'LH Hotel (Double Room Shack)', lateCheckout: false, bedConfiguration: null },
  { id: 'today-in-2',  roomId: '15', guestName: 'Korsgaard, Craig',    checkIn: '2026-03-09', checkOut: '2026-05-03', adults: 1, children: 0, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CONFIRMED',   isUnallocated: true,  outstandingBalance: null,    paymentExpired: false, roomDisplayName: null, lateCheckout: false, bedConfiguration: null },
  { id: 'today-in-3',  roomId: '3',  guestName: 'Geidt, Ann',          checkIn: '2026-03-09', checkOut: '2026-03-12', adults: 2, children: 2, infants: 1, reservationStatus: 'CONFIRMED', guestStatus: 'CONFIRMED',   isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room Shack)', lateCheckout: false, bedConfiguration: null },
  { id: 'today-out-2', roomId: '4',  guestName: 'Madsen, Lydia Rhiel', checkIn: '2026-03-04', checkOut: '2026-03-09', adults: 1, children: 0, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CHECKED_OUT', isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room Shack)', lateCheckout: false, bedConfiguration: null },
  { id: 'today-in-h1', roomId: '5',  guestName: 'Vaccaro, Rayna',      checkIn: '2026-03-05', checkOut: '2026-03-14', adults: 2, children: 1, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Double Room Shack)', lateCheckout: false, bedConfiguration: null },
  { id: 'today-in-h2', roomId: '6',  guestName: 'Nguyen, Peter',       checkIn: '2026-03-06', checkOut: '2026-03-13', adults: 3, children: 0, infants: 0, reservationStatus: 'CONFIRMED', guestStatus: 'CHECKED_IN',  isUnallocated: false, outstandingBalance: null,    paymentExpired: false, roomDisplayName: 'LH Hotel (Standard Twin)', lateCheckout: false, bedConfiguration: null },
];
